version: '3.8'

services:
  app:
    container_name: tecapp
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo01
      - mongo02
      - mongo03
      - mongo04
      - redis01
    environment:
      - MONGO_URI=mongodb://mongo01:27017,mongo02:27018,mongo03:27019,mongo04:27020/tec?replicaSet=rs0&serverSelectionTimeoutMS=60000
      - REDIS_HOST=redis01
      - REDIS_PORT=6379
      - PORT=3000
    networks:
      - red01

  mongo01:
    container_name: mongo01
    image: mongo:latest
    command: mongod --replSet rs0 --bind_ip_all
    ports:
      - "27017:27017"
    networks:
      - red01

  mongo02:
    container_name: mongo02
    image: mongo:latest
    command: sh -c "sleep 30 && mongod --replSet rs0 --bind_ip_all"
    ports:
      - "27018:27017"
    networks:
      - red01

  mongo03:
    container_name: mongo03
    image: mongo:latest
    command: sh -c "sleep 30 && mongod --replSet rs0 --bind_ip_all"
    ports:
      - "27019:27017"
    networks:
      - red01

  mongo04:
    container_name: mongo04
    image: mongo:latest
    command: sh -c "sleep 30 && mongod --replSet rs0 --bind_ip_all"
    ports:
      - "27020:27017"
    networks:
      - red01

  redis01:
    container_name: redis01
    image: redis:latest
    ports:
      - "6379:6379"
    depends_on:
      - mongo01
      - mongo02
      - mongo03
      - mongo04
    networks:
      - red01

networks:
  red01:
    driver: bridge
